chess/urls.py
from django.conf.urls import url, include, patterns
from django.contrib import admin
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = i18n_patterns('',
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^adminstration/', include(admin.site.urls)),
    url(r'^', include('userprofile.urls')),
    url(r'^', include('home.urls')),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += staticfiles_urlpatterns()




@login_required
def protected_serve(request, path, document_root=None, show_indexes=False):
    return serve(request, path, document_root, show_indexes)



urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG is False:   #if DEBUG is True it will be served automatically
    urlpatterns += [
            url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
            url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
            # url(r'^i18n/', include('django.conf.urls.i18n')),
            #url(r'^site_media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT }),
    ]

home/urls.py
from django.conf.urls import url, include
# from django.contrib.auth import logout
from home.views import *
from userprofile.views import *

urlpatterns = [
    url(r'^$', home, name='index'),
    url(r'^apply/$', apply, name='apply'),
    url(r'^blog/$', blog, name='blog'),
    url(r'^news/$', news, name='news'),
    url(r'^tournaments/$', tournaments, name='tournaments'),
    url(r'^blog/tournament/(?P<n_id>\d+)/(?P<n_slug>[\w-]+)$', tournament, name='tournament'),
    url(r'^blog/category/(?P<c_id>\d+)/$', blog_category, name='blog_category'),
    url(r'^blog/news/(?P<n_id>\d+)/(?P<n_slug>[\w-]+)$', blog_news, name='blog_news'),
    url(r'^about-vugar/(?P<v_slug>[\w-]+)$', about_vuqar, name='about_vuqar'),
    ]

home/models.py
from django.db import models
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
from django.utils.timezone import datetime


class SiteInformation(models.Model):
    site_name = models.CharField(max_length=255)
    site_url = models.IntegerField()
    # active = models.BooleanField()
    meta_description = models.TextField(blank=True, null=True)
    meta_keywords = models.TextField(blank=True, null=True)
    # slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.site_name

    def get_images(self):
        return SliderImage.objects.filter(slider=self, active=True).order_by('order_index')

class Category(models.Model):
    name = models.CharField(max_length=255)
    order_index = models.IntegerField()
    active = models.BooleanField()
    description = models.TextField(blank=True, null=True)
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name
    def get_images(self):
        return SliderImage.objects.filter(slider=self, active=True).order_by('order_index')


class Blog(models.Model):
    category = models.ForeignKey('Category')
    title = models.CharField(max_length=255)
    short_text = models.TextField(max_length=500)
    image = models.ImageField(upload_to='blog/post/')
    active = models.BooleanField()
    content = RichTextUploadingField(config_name='awesome_ckeditor')
    publish_start_date = models.DateTimeField(null=False,default=datetime.now())
    publish_end_date = models.DateTimeField(null=True,blank=True)
    meta_description = models.CharField(max_length=1024,blank=True)
    meta_keywords = models.CharField(max_length=1024,blank=True)
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.title


date = models.DateTimeField(auto_now_add=True)


def get_images(self):
    return SliderImage.objects.filter(slider=self, active=True).order_by('order_index')


class Slider(models.Model):
    title = models.CharField(max_length=255)
    active = models.BooleanField()
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.title

    def get_images(self):
        return SliderImage.objects.filter(slider=self, active=True).order_by('order_index')


class SliderImage(models.Model):
    slider = models.ForeignKey('Slider')
    # title = models.CharField(max_length=255,blank=True,null=True)
    order_index = models.IntegerField()
    # content = models.TextField(blank=True, null=True,editable=True)
    image = models.ImageField(upload_to='slider-image')
    url = models.URLField(blank=True, null=True)
    active = models.BooleanField()
    date = models.DateTimeField(auto_now_add=True)


class Apply(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    birth_date = models.DateField(auto_now_add=False, auto_now=False)
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    is_read = models.BooleanField(default=False)
    def __str__(self):
        return '{} - {}'.format(self.first_name,self.last_name)


class Tournament(models.Model):
    title = models.CharField(max_length=255)
    short_text = models.TextField(max_length=500)
    image = models.ImageField(upload_to='tournament/post/')
    active = models.BooleanField()
    content = RichTextUploadingField(config_name='awesome_ckeditor')
    publish_start_date = models.DateTimeField(null=False,default=datetime.now())
    tournament_date = models.DateTimeField()
    publish_end_date = models.DateTimeField(null=True,blank=True)
    meta_description = models.CharField(max_length=1024,blank=True)
    meta_keywords = models.CharField(max_length=1024,blank=True)
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.title

İCON_CHOICES = (
              ('socialicon socialicon-facebook', "Facebook"),
              ('socialicon socialicon-instagram', "İnstagram"),
              ('socialicon socialicon-youtube', "Youtube"),
              ('socialicon socialicon-twitter', "Twitter"),
              ('socialicon socialicon-google', "Google Plus"),
             )

class Social(models.Model):
    name = models.CharField(max_length=255)
    icon_class = models.CharField(max_length=255,choices=İCON_CHOICES)
    order_index = models.IntegerField()
    url = models.URLField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name


class VugarPage(models.Model):
    active = models.BooleanField()
    full_name = models.CharField(max_length=255)
    # short_description = RichTextUploadingField(config_name='awesome_ckeditor',blank=True,null=True)
    # portrait_image = models.ImageField(upload_to='vugar/portrait/',blank=True,)
    biography = RichTextUploadingField(config_name='awesome_ckeditor',blank=True,null=True)
    titles = RichTextUploadingField(config_name='awesome_ckeditor',blank=True,null=True)
    # participan = RichTextUploadingField(config_name='awesome_ckeditor',blank=True,null=True)
    aphorism = RichTextUploadingField(config_name='awesome_ckeditor',blank=True,null=True)
    vuqar_in_the_world = RichTextUploadingField(config_name='awesome_ckeditor',blank=True,null=True)
    genius = RichTextUploadingField(config_name='awesome_ckeditor',blank=True,null=True)
    disinterested_human = RichTextUploadingField(config_name='awesome_ckeditor',blank=True,null=True)
    vugar_museum = RichTextUploadingField(config_name='awesome_ckeditor',blank=True,null=True)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.full_name
    def get_museum_images(self):
        return VugarPageMuseumPhoto.objects.filter(vugar_page=self)
    def get_photos(self):
        return VugarPagePhoto.objects.filter(vugar_page=self)
    def get_childhood_photos(self):
        return VugarChildhoodPhoto.objects.filter(vugar_page=self)
    # def get_genius_photos(self):
    #     return VugarGeniusPhoto.objects.filter(vugar_page=self)
    # def get_participan_photos(self):
    #     return VugarParticipanPhoto.objects.filter(vugar_page=self)
    def get_disinterested_human_photos(self):
        return VugarDisinterestedHumanPhoto.objects.filter(vugar_page=self)

class VugarPagePhoto(models.Model):
    vugar_page = models.ForeignKey('VugarPage')
    short_description = models.CharField(max_length=500,blank=True,null=True)
    photo = models.ImageField(upload_to='vugar/photos/')
    date = models.DateTimeField(auto_now_add=True)

class VugarPageMuseumPhoto(models.Model):
    vugar_page = models.ForeignKey('VugarPage')
    short_description = models.CharField(max_length=500,blank=True,null=True)
    photo = models.ImageField(upload_to='vugar/museum/')
    date = models.DateTimeField(auto_now_add=True)

class VugarChildhoodPhoto(models.Model):
    vugar_page = models.ForeignKey('VugarPage')
    short_description = models.CharField(max_length=500,blank=True,null=True)
    photo = models.ImageField(upload_to='vugar/childhood/')
    date = models.DateTimeField(auto_now_add=True)

# class VugarGeniusPhoto(models.Model):
#     vugar_page = models.ForeignKey('VugarPage')
#     short_description = models.CharField(max_length=500,blank=True,null=True)
#     photo = models.ImageField(upload_to='vugar/genius/')
#     date = models.DateTimeField(auto_now_add=True)

# class VugarParticipanPhoto(models.Model):
#     vugar_page = models.ForeignKey('VugarPage')
#     short_description = models.CharField(max_length=500,blank=True,null=True)
#     photo = models.ImageField(upload_to='vugar/participan/')
#     date = models.DateTimeField(auto_now_add=True)

class VugarDisinterestedHumanPhoto(models.Model):
    vugar_page = models.ForeignKey('VugarPage')
    short_description = models.CharField(max_length=500,blank=True,null=True)
    photo = models.ImageField(upload_to='vugar/disinterested-human/')
    date = models.DateTimeField(auto_now_add=True)

home/forms.py
from django import forms
from captcha.fields import ReCaptchaField

from django.utils.translation import ugettext_lazy as _

class ApplyForm(forms.Form):
    first_name = forms.CharField( required=True,widget=forms.TextInput(attrs={'placeholder': _('Your Firstname: *')}))
    last_name = forms.CharField( required=True,widget=forms.TextInput(attrs={'placeholder': _('Your Lastname: *')}))
    phone = forms.CharField( required=True,widget=forms.TextInput(attrs={'placeholder': _('Phone: *')}))
    birth_date = forms.DateField(widget=forms.DateInput(attrs={'placeholder': _('Birth Date: *')}))
    message = forms.CharField(widget=forms.Textarea(attrs={'placeholder': _('Message: *')}),required=False)
    # captcha = ReCaptchaField()

templates/home/apply.html
{% extends 'main_base.html' %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}
{% block head_block %}

    <link href="{% static 'mainsection/datepicker/css/bootstrap-datepicker.css' %}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.6.5/sweetalert2.min.css"
          type="text/css"/>
{% endblock %}

{% block content_block %}

{#    <section class="main__middle__container section-container-backgorund-color">#}

        <section class="contact-us  section-row-backgorund-image">
        <div class="row title__block  section-row-backgorund-image" style="padding: 0px 0 0px 0;">
            <div class="container text-center section-container-backgorund-color">
                <h2 class="page__title"><span>{% trans 'apply' %}</span></h2>
                <span class="sep"></span>
                <p class="smaller">
                    {% trans 'learn_chess_with_vugar_gashimov_chess_academy' %}
                </p>
            </div>
        </div>
            <div class="container section-container-backgorund-color">
                <div class="row">
                    <div class="col-md-8">
                        <h3>{% trans 'apply_as'|title %} </h3>
                        <hr/>
                        <p></p>
                        <br/>
                        <p id="feedback"/>
                        <form role="form" id="contact-form" name="contact-form" method="post" action=""
                              class="contact-form">
                            {% csrf_token %}
                            <div class="form-group col-md-6" style="padding: 0 20px 0 0;">
                                <label class="sr-only" for="exampleInputEmail1">{% trans 'Your Firstname: *' %} </label>
                                {{ apply_form.first_name|add_class:'form-control' }}
                                {% if apply_form.first_name.errors %}
                                    <div class="alert alert-danger" style="padding: 7px 0;">
                                        <button style="margin: 5px 10px;" type="button" class="close"
                                                data-dismiss="alert" aria-hidden="true">
                                            ×
                                        </button>
                                        <strong>{{ apply_form.first_name.errors }}</strong>
                                    </div>
                                {% endif %}
                            </div>
                            <div class="form-group col-md-6">
                                <label class="sr-only" for="exampleInputEmail1">{% trans 'Your Lastname: *' %} </label>
                                {{ apply_form.last_name|add_class:'form-control' }}
                                {% if apply_form.last_name.errors %}
                                    <div class="alert alert-danger" style="padding: 7px 0;">
                                        <button style="margin: 5px 10px;" type="button" class="close"
                                                data-dismiss="alert" aria-hidden="true">
                                            ×
                                        </button>
                                        <strong>{{ apply_form.last_name.errors }}</strong>
                                    </div>
                                {% endif %}
                            </div>
                            <div class="clearfix"></div>
                            <div class="form-group col-md-6">
                                <label class="sr-only" for="exampleInputEmail1">{% trans 'Phone: *' %}</label>
                                {{ apply_form.phone|add_class:'form-control' }}
                                {% if apply_form.phone.errors %}
                                    <div class="alert alert-danger" style="padding: 7px 0;">
                                        <button style="margin: 5px 10px;" type="button" class="close"
                                                data-dismiss="alert" aria-hidden="true">
                                            ×
                                        </button>
                                        <strong>{{ apply_form.phone.errors }}</strong>
                                    </div>
                                {% endif %}
                            </div>
                            <div class="form-group col-md-6">
                                <label class="sr-only" for="exampleInputEmail1">{% trans 'Birth Date: *' %}</label>
                                <div class="input-group date" data-provide="datepicker">
                                    {{ apply_form.birth_date|add_class:'form-control' }}
                                    <div class="input-group-addon">
                                        <span class="glyphicon glyphicon-th"></span>
                                    </div>
                                </div>
                                {% if apply_form.birth_date.errors %}
                                    <div class="alert alert-danger" style="padding: 7px 0;">
                                        <button style="margin: 5px 10px;" type="button" class="close"
                                                data-dismiss="alert" aria-hidden="true">
                                            ×
                                        </button>
                                        <strong>{{ apply_form.birth_date.errors }}</strong>
                                    </div>
                                {% endif %}
                            </div>
                            <div class="clearfix"></div>
                            <div class="form-group">
                                {{ apply_form.message|add_class:'form-control'|attr:'rows:5' }}
                                {% if apply_form.message.errors %}
                                    <div class="alert alert-danger" style="padding: 7px 0;">
                                        <button style="margin: 5px 10px;" type="button" class="close"
                                                data-dismiss="alert" aria-hidden="true">
                                            ×
                                        </button>
                                        <strong>{{ apply_form.message.errors }}</strong>
                                    </div>
                                {% endif %}
                            </div>
                            <input id="submit-button" type="submit" class="btn btn-lg btn-info"
                                   value="{% trans 'apply' %}"/>
                        </form>
                    </div>
                    <div class="col-md-4">
                        <h3>{% trans 'contact' %} </h3>
                        <hr/>
                        <p class="black-text">
                            Bakı şəhəri, Yasamal rayonu,<br/>
                            Bəsti Bağirova 2<br/>
                            Dövlət Statistika komitəsi ilə üzbəüz <br/>
                        </p>
                        <p class="black-text"><span class="orange">{% trans 'phone'|title %}: </span> +994 (050) 353-10-10
                        </p>
                        <p class="black-text"><span class="orange">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span> +994 (070) 353-10-10
                        </p>
                        <p class="black-text"><span class="orange">{% trans 'telephone'|title %}: </span> +994 (012)
                            436-86-10 </p>
                        <div class="social__icons">
                            {% for base_social in base_socials %}
                                <a target="_blank" href="{{ base_social.url }}"
                                   class="{{ base_social.icon_class }}"></a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3039.100738058975!2d49.82407345075594!3d40.384459879267645!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40307d9a3628e64f%3A0xe3f6733413012399!2zVsO8cWFyIEjJmcWfaW1vdiDFnmFobWF0IEFrYWRlbWl5YXPEsQ!5e0!3m2!1sen!2s!4v1507717830657"
                        width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
        </section>
{#    </section>#}

{% endblock %}

{% block footer_block %}
    <script src="{% static 'mainsection/datepicker/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.6.5/sweetalert2.min.js"></script>

    <script>
        $(document).ready(function () {
            {% if post_message and post_message_code %}
            swal(
                'Uğurlu!',
                '{{ post_message }}',
                '{% if post_message_code == 1 %}success{% elif post_message_code == 0 %}error{% endif %}'
            );
            {% endif %}
        });

        $('#id_birth_date').datepicker({
            format: 'yyyy-mm-dd',
            autoclose: true,
            {#    startDate: '-3d'#}
        });
    </script>
{% endblock %}

templates/home/blog.html
{% extends 'main_base.html' %}
{% load static %}
{% load i18n %}

{% block head_block %}

    <link href="{% static 'mainsection/shortcodes/shortcodes.css' %}" rel="stylesheet"/>
{% endblock %}

{% block content_block %}

    <section class="main__middle__container">
        <section class="recent-posts section-row-backgorund-image">
            <div class="container section-container-backgorund-color">
                <div class="row no-margin nothing">
                    <h2 class="page__title text-center"><span>{% trans 'blog'|title %} {% if category %} >
                        {{ category.name }}{% endif %}</span></h2>
                    <p class="small-paragraph text-center">
                        {% if category %}{% trans 'blog_description' %}{% endif %}
                    </p>
                    <div class="col-md-9">
                        {% for blog in blogs %}
                            <article>
                                <img src="{{ blog.image.url }}" alt="{{ blog.title }}"
                                     class="pull-left img-responsive"/>
                                <div class="text">
                                    {#                                    <p class="small-paragraph">Lorem ipsum dolor sit </p>#}
                                    <h3>
                                        <a href="{% url 'blog_news' blog.id blog.slug %}">
                                            {{ blog.title }}
                                        </a>
                                    </h3>
                                    <p>
                                        {{ blog.short_text }}
                                    </p>
                                    <h3>
                                        <small>
                                            <a href="{% url 'blog_news' blog.id blog.slug %}">
                                                {% trans 'read_more' %}
                                            </a>
                                        </small>
                                    </h3>
                                </div>
                                <div class="clearfix"></div>
                            </article>
                        {% endfor %}
                    </div>
                    <div class="col-md-3">

                        <table class="dc_table_s10" summary="Sample Table" style="width:100%;margin-bottom: 20px;">
                            <thead>
                            <tr>
                                <th style="text-align: center;" scope="col">{% trans 'categories'|title %}</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for category in categories %}
                                <tr style="cursor: pointer;"
                                    onclick="window.location.replace('{% url 'blog_category' category.id %}');">
                                    <td class="{% if forloop.counter|divisibleby:2 %}odd{% endif %}">{{ category.name }}</td>
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                        {% include 'home/include/_last_tourments.html' %}
                    </div>
                </div>
            </div>
        </section>
    </section>

{% endblock %}

{% block footer_block %}


{% endblock %}

templates/home/blog_news.html
{% extends 'main_base.html' %}

{% block head_block %}


{% endblock %}

{% block content_block %}


    <section class="main__middle__container">
        <div class="container">
            <div class="row nothing">
                <section class="col-sm-8 col-md-9 col-xs-12 main-content">
                    <h2>{{ news.title }} </h2>
                    <img src="{{ news.image.url }}" alt="image" class="img-responsive"/> <br/>
                    {% autoescape off %}
                        {{ news.content }}
                    {% endautoescape %}

                    <br/>
                </section>
                <aside class="col-md-3 col-sm-4 col-xs-12">
                    {% include 'home/include/_last_blogs.html' %}
                </aside>
            </div>
        </div>
    </section>
{% endblock %}

{% block footer_block %}


{% endblock %}

templates/home/news.html
{% extends 'main_base.html' %}
{% load static %}
{% load i18n %}

{% block head_block %}

    <link href="{% static 'mainsection/shortcodes/shortcodes.css' %}" rel="stylesheet"/>
{% endblock %}

{% block content_block %}

    <section class="main__middle__container">
        <section class="recent-posts section-row-backgorund-image">
            <div class="container section-container-backgorund-color">
                <div class="row no-margin nothing">
                    <h2 class="page__title text-center"><span>{% trans 'news'|title %}</span></h2>
{#                    <p class="small-paragraph text-center">#}
{#                        {% trans 'tournaments'|title %}#}
{#                    </p>#}
                    <div class="col-md-9">
                        {% for tournament in tournaments %}
                            <article>
                                <img src="{{ tournament.image.url }}" alt="pic1"
                                     class="pull-left img-responsive"/>
                                <div class="text">
                                    {#                                    <p class="small-paragraph">Lorem ipsum dolor sit </p>#}
                                    <h3>
                                        <a href="{% url 'tournament' tournament.id tournament.slug %}">
                                            {{ tournament.title }}
                                        </a>
                                    </h3>
                                    <p>
                                        {{ tournament.short_text }}
                                    </p>
                                    <h3>
                                        <small>
                                            <a href="{% url 'tournament' tournament.id tournament.slug %}">
                                                {% trans 'read_more' %}
                                            </a>
                                        </small>
                                    </h3>
                                </div>
                                <div class="clearfix"></div>
                            </article>
                        {% endfor %}
                    </div>
                    <div class="col-md-3">
                        {% include 'home/include/_last_blogs.html' %}
                    </div>
                </div>
            </div>
        </section>
    </section>

{% endblock %}

{% block footer_block %}


{% endblock %}

templates/home/test.html
{% extends 'main_base.html' %}

{% block head_block %}


{% endblock %}

{% block content_block %}


{% endblock %}

{% block footer_block %}


{% endblock %}

templates/home/tournament.html
{% extends 'main_base.html' %}

{% block head_block %}


{% endblock %}

{% block content_block %}


    <section class="main__middle__container">
        <div class="container">
            <div class="row nothing">
                <section class="col-sm-8 col-md-9 col-xs-12 main-content">
                    <h2>{{ tournament.title }} </h2>
                    <img src="{{ tournament.image.url }}" alt="image" class="img-responsive"/> <br/>
                    {% autoescape off %}
                        {{ tournament.content }}
                    {% endautoescape %}

                    <br/>
                </section>
                <aside class="col-md-3 col-sm-4 col-xs-12">
                    {% include 'home/include/_last_tourments.html' %}
                </aside>
            </div>
        </div>
    </section>
{% endblock %}

{% block footer_block %}


{% endblock %}

templates/home/tournaments.html
{% extends 'main_base.html' %}
{% load static %}
{% load i18n %}

{% block head_block %}

    <link href="{% static 'mainsection/shortcodes/shortcodes.css' %}" rel="stylesheet"/>
{% endblock %}

{% block content_block %}

    <section class="main__middle__container">
        <section class="recent-posts section-row-backgorund-image">
            <div class="container section-container-backgorund-color">
                <div class="row no-margin nothing">
                    <h2 class="page__title text-center"><span>{% trans 'tournaments'|title %}</span></h2>
{#                    <p class="small-paragraph text-center">#}
{#                        {% trans 'tournaments'|title %}#}
{#                    </p>#}
                    <div class="col-md-9">
                        {% for tournament in tournaments %}
                            <article>
                                <img src="{{ tournament.image.url }}" alt="pic1"
                                     class="pull-left img-responsive"/>
                                <div class="text">
                                    {#                                    <p class="small-paragraph">Lorem ipsum dolor sit </p>#}
                                    <h3>
                                        <a href="{% url 'tournament' tournament.id tournament.slug %}">
                                            {{ tournament.title }}
                                        </a>
                                    </h3>
                                    <p>
                                        {{ tournament.short_text }}
                                    </p>
                                    <h3>
                                        <small>
                                            <a href="{% url 'tournament' tournament.id tournament.slug %}">
                                                {% trans 'read_more' %}
                                            </a>
                                        </small>
                                    </h3>
                                </div>
                                <div class="clearfix"></div>
                            </article>
                        {% endfor %}
                    </div>
                    <div class="col-md-3">
                        {% include 'home/include/_last_blogs.html' %}
                    </div>
                </div>
            </div>
        </section>
    </section>

{% endblock %}

{% block footer_block %}


{% endblock %}